'use strict';
/** @module run-perf — Six-stage standalone performance pipeline: generate scripts, execute k6, evaluate thresholds, sync to Zephyr, generate report, git sync. */

require('dotenv').config();
const fs   = require('fs');
const path = require('path');
const logger = require('../src/utils/logger');
const { perf: perfConfig } = require('../src/core/config');

const ROOT = path.resolve(__dirname, '..');

// ─── Flag parsing ────────────────────────────────────────────────────────────
const args     = process.argv.slice(2);
const flagSet  = new Set(args.map(a => a.toLowerCase()));

function getFlag(prefix) {
  const a = args.find(a => a.startsWith(prefix));
  return a ? a.slice(prefix.length) : undefined;
}

const flags = {
  skipGenerate: flagSet.has('--skip-generate'),
  skipSync:     flagSet.has('--skip-sync'),
  skipBugs:     flagSet.has('--skip-bugs'),
  skipReport:   flagSet.has('--skip-report'),
  skipGit:      flagSet.has('--skip-git'),
  testType:     getFlag('--test-type='),
  story:        getFlag('--story='),
  dryRun:       flagSet.has('--dry-run'),
};

// ─── ANSI helpers ─────────────────────────────────────────────────────────────
const C = {
  reset: '\x1b[0m', bold: '\x1b[1m', dim: '\x1b[2m',
  green: '\x1b[32m', yellow: '\x1b[33m', red: '\x1b[31m',
  cyan: '\x1b[36m', blue: '\x1b[34m', white: '\x1b[97m',
};

function now()      { return new Date().toLocaleTimeString('en-GB', { hour12: false }); }
function elapsed(t) { return ((Date.now() - t) / 1000).toFixed(1); }

function stageLog(num, label, status = 'RUNNING') {
  const col = status === 'SKIPPED' ? C.yellow : status.startsWith('DONE') ? C.green : C.cyan;
  console.log(`\n${C.bold}${C.white}Stage ${num} — ${label}${C.reset}  ${col}${status}${C.reset}  ${C.dim}[${now()}]${C.reset}`);
}

// ─── Glob helper ─────────────────────────────────────────────────────────────
function findK6Scripts(dir, typeFilter) {
  const results = [];
  if (!fs.existsSync(dir)) return results;
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      results.push(...findK6Scripts(full, typeFilter));
    } else if (entry.name.endsWith('.k6.js')) {
      if (!typeFilter || full.includes(path.sep + typeFilter + path.sep)) {
        results.push(full);
      }
    }
  }
  return results;
}

// ─── Post-execution assertion pass ───────────────────────────────────────────
function postExecutionAssertions(metrics, _storyKey) {
  const issues = [];
  const configuredVusMax = perfConfig.vusMax;

  if ((metrics.reqCount || 0) < 1) {
    issues.push('no successful requests recorded');
  }
  if ((metrics.droppedIterations || 0) >= 5) {
    issues.push(`dropped_iterations=${metrics.droppedIterations} >= 5`);
  }
  // Only enforce VU cap when PERF_VUS_MAX is explicitly configured (not the built-in default).
  // Scripts generated by the agent may use fewer VUs than the platform default of 50.
  if (process.env.PERF_VUS_MAX && (metrics.vusMax || 0) > 0) {
    const vuDiff = Math.abs((metrics.vusMax || 0) - configuredVusMax);
    if (configuredVusMax > 0 && vuDiff > 1) {
      issues.push(`vusMax=${metrics.vusMax} differs from PERF_VUS_MAX=${configuredVusMax} by more than ±1`);
    }
  }

  return issues;
}

// ─── Execute a single script (returns result object) ─────────────────────────
async function runOneScript(scriptPath, outBaseDir, thresholdsByType, _globalThresholds) {
  const {
    runPerfTest, parsePerfResults, evaluateThresholds, compareToBaseline,
    saveThresholdsForRun, resolveThresholds,
  } = require('../src/services/perf.execution.service');

  const basename    = path.basename(scriptPath, '.k6.js');
  const outJsonPath = path.join(outBaseDir, `${basename}.json`);
  const parts       = basename.split('_');
  const testType    = parts[parts.length - 1] || 'load';
  const storyKey    = parts.slice(0, -1).join('_') || process.env.ISSUE_KEY || 'UNKNOWN';

  // Pass null so resolveThresholds always reaches perfConfig.thresholds[testType] first.
  // globalThresholds (legacyThresholds) has p95>0 which would short-circuit the testType lookup.
  const activeThresholds = thresholdsByType
    ? (thresholdsByType[testType] || resolveThresholds(null, testType))
    : resolveThresholds(null, testType);

  if (flags.dryRun) {
    const k6 = perfConfig.k6Binary;
    const rel = path.relative(ROOT, scriptPath);
    console.log(`  ${C.cyan}[DRY-RUN]${C.reset} ${k6} run --out json=test-results/perf/${basename}.json --summary-export test-results/perf/${basename}-summary.json ${rel}`);
    return { scriptPath, basename, testType, storyKey, dryRun: true, verdict: 'pass', metrics: {}, breaches: [], warnings: [] };
  }

  const tStart = Date.now();
  console.log(`  Running: ${basename}`);
  try {
    const runResult = await runPerfTest(scriptPath, outJsonPath, {
      BASE_URL: process.env.BASE_URL || 'https://test.k6.io',
      VUS:      process.env.PERF_VUS_MAX,
    });

    if (runResult.skipped) {
      console.log(`  ${C.yellow}⟳ Skipped (soak): ${basename}${C.reset}`);
      return { scriptPath, basename, testType, storyKey, skipped: true };
    }

    const metrics = parsePerfResults(outJsonPath);
    saveThresholdsForRun(storyKey, testType, activeThresholds);

    // ── Stage 2b: post-execution assertions ──────────────────────────────────
    const assertIssues = postExecutionAssertions(metrics, storyKey);
    if (assertIssues.length > 0) {
      logger.warn(`[run-perf] Post-execution assertions failed for ${basename}: ${assertIssues.join('; ')}`);
      console.warn(`  ${C.yellow}⚠ Data-invalid (${assertIssues.join('; ')}) — skipping SLA verdict for ${basename}${C.reset}`);
      return {
        scriptPath, basename, testType, storyKey,
        metrics, verdict: 'data-invalid', breaches: [], warnings: [],
        assertIssues,
      };
    }

    const { verdict, breaches, warnings } = evaluateThresholds(metrics, activeThresholds, testType);
    const baseline = compareToBaseline(`${storyKey}_${testType}`, metrics);

    const elapsed_ms = Date.now() - tStart;
    console.log(`  ${C.dim}  └ ${testType} finished in ${(elapsed_ms / 1000).toFixed(1)}s — verdict: ${verdict}${C.reset}`);

    return {
      scriptPath, basename, testType, storyKey,
      metrics, verdict, breaches, warnings,
      baselineDegraded:           baseline.degraded,
      previousP95:                baseline.previousP95,
      changePct:                  baseline.changePct,
      baselineDegradedP99:        baseline.baselineDegradedP99,
      previousP99:                baseline.previousP99,
      changePct99:                baseline.changePct99,
      baselineDegradedAvg:        baseline.baselineDegradedAvg,
      baselineErrorRateIncreased: baseline.baselineErrorRateIncreased,
      previousErrorRate:          baseline.previousErrorRate,
      trend:                      baseline.trend,
      historyWindow:              baseline.historyWindow,
      changePctAvg:               baseline.changePctAvg,
    };
  } catch (err) {
    logger.error(`[run-perf] Script failed: ${basename}: ${err.message}`);
    console.error(`  ${C.red}✗ ${basename}: ${err.message}${C.reset}`);
    let metrics = {};
    try {
      const { parsePerfResults: pp } = require('../src/services/perf.execution.service');
      if (fs.existsSync(outJsonPath)) metrics = pp(outJsonPath);
    } catch { /* leave empty */ }
    return { scriptPath, basename, testType, storyKey, verdict: 'fail', breaches: [], warnings: [], metrics };
  }
}

// ─── Main pipeline ────────────────────────────────────────────────────────────
async function main() {
  const pipelineStart = Date.now();
  let totalRun = 0, passCount = 0, warnCount = 0, failCount = 0;

  console.log(`\n${C.bold}${C.blue}╔══════════════════════════════════════════════════════╗`);
  console.log(`║  Agentic QA — Performance Pipeline (6 stages)       ║`);
  console.log(`║  Test types: load|stress|spike|soak|scalability      ║`);
  console.log(`║             breakpoint                                ║`);
  if (flags.dryRun) console.log(`║  ${C.yellow}DRY-RUN MODE — no k6 execution${C.reset}${C.bold}${C.blue}                      ║`);
  console.log(`╚══════════════════════════════════════════════════════╝${C.reset}\n`);

  const globalThresholds = perfConfig.legacyThresholds;
  let thresholdsByType = null;

  const allResults = [];

  // ──────────────────────────────────────────────────────────────────────────
  // Stage 1 — Generate k6 scripts
  // ──────────────────────────────────────────────────────────────────────────
  stageLog(1, 'Generate k6 performance scripts', flags.skipGenerate ? 'SKIPPED' : 'RUNNING');
  const s1 = Date.now();
  if (!flags.skipGenerate) {
    try {
      const genModule = require('./generate-perf-scripts');
      const genResult = await genModule.run({
        storyKey: process.env.ISSUE_KEY,
        baseUrl:  process.env.BASE_URL || 'https://test.k6.io',
        testType: flags.testType,
      });
      if (!genResult.perfRequired) {
        console.log(`  ${C.yellow}No performance signals found — no scripts generated.${C.reset}`);
      } else {
        console.log(`  ${C.green}Generated ${genResult.scripts.length} script(s).${C.reset}`);
        if (genResult.thresholdsByType) {
          thresholdsByType = genResult.thresholdsByType;
          logger.info('[run-perf] Per-type thresholds loaded from agent');
        }
      }
    } catch (err) {
      logger.error(`[run-perf] Stage 1 error: ${err.message}`);
      console.error(`  ${C.red}Stage 1 failed: ${err.message}${C.reset}`);
    }
  }
  stageLog(1, 'Generate k6 performance scripts', `DONE (${elapsed(s1)}s)`);

  // ──────────────────────────────────────────────────────────────────────────
  // Stage 2 — Execute k6 scripts (parallel gate + sequential breakpoint)
  // ──────────────────────────────────────────────────────────────────────────
  stageLog(2, 'Execute k6 scripts', flags.dryRun ? 'DRY-RUN' : 'RUNNING');
  const s2 = Date.now();

  const perfDir    = path.join(ROOT, 'tests', 'perf');
  const outBaseDir = path.join(ROOT, 'test-results', 'perf');
  fs.mkdirSync(outBaseDir, { recursive: true });

  let scripts = findK6Scripts(perfDir, flags.testType);
  // Optional story scope: only run scripts whose basename storyKey matches --story=<key>.
  // Basename is "<storyKey>_<testType>"; strip the trailing _<testType> to get the storyKey.
  if (flags.story) {
    scripts = scripts.filter(s => path.basename(s, '.k6.js').replace(/_[^_]+$/, '') === flags.story);
  }
  if (scripts.length === 0) {
    console.log(`  ${C.yellow}No k6 scripts found in tests/perf/${flags.story ? ` for story ${flags.story}` : ''}.${C.reset}`);
  }

  // Categorise scripts for parallel execution gate (Stage 2c)
  function typeOf(p) { const parts = path.basename(p, '.k6.js').split('_'); return parts[parts.length - 1]; }

  const loadScripts         = scripts.filter(s => ['load', 'stress'].includes(typeOf(s)));
  const spikeScripts        = scripts.filter(s => typeOf(s) === 'spike');
  const soakScripts         = scripts.filter(s => typeOf(s) === 'soak' && !perfConfig.skipSoak);
  const skippedSoakScripts  = scripts.filter(s => typeOf(s) === 'soak' &&  perfConfig.skipSoak);
  // scalability and breakpoint run sequentially after load/stress/spike/soak
  const sequentialScripts   = scripts.filter(s => ['scalability', 'breakpoint'].includes(typeOf(s)));

  async function runGroup(group, label) {
    if (group.length === 0) return;
    const gStart = Date.now();
    console.log(`  ${C.dim}→ Running ${label} in parallel (${group.length} scripts)${C.reset}`);
    const results = await Promise.all(group.map(sp => runOneScript(sp, outBaseDir, thresholdsByType, globalThresholds)));
    allResults.push(...results);
    console.log(`  ${C.dim}  ${label} done in ${elapsed(gStart)}s${C.reset}`);
  }

  // skip-soak placeholder entries
  for (const sp of skippedSoakScripts) {
    console.log(`  ${C.yellow}⟳ Skipped (PERF_SKIP_SOAK=true): ${path.basename(sp)}${C.reset}`);
    allResults.push({ scriptPath: sp, basename: path.basename(sp, '.k6.js'), skipped: true });
  }

  // Stage 2c: parallel execution gate
  await runGroup(loadScripts, 'load + stress');
  for (const sp of spikeScripts) {
    allResults.push(await runOneScript(sp, outBaseDir, thresholdsByType, globalThresholds));
  }
  await runGroup(soakScripts, 'soak');
  for (const sp of sequentialScripts) {
    allResults.push(await runOneScript(sp, outBaseDir, thresholdsByType, globalThresholds));
  }

  stageLog(2, 'Execute k6 scripts', `DONE (${elapsed(s2)}s)`);

  // ──────────────────────────────────────────────────────────────────────────
  // Stage 3 — Evaluate thresholds + baseline comparison
  // ──────────────────────────────────────────────────────────────────────────
  stageLog(3, 'Evaluate thresholds + baseline comparison', 'RUNNING');
  const s3 = Date.now();
  const { updateBaseline } = require('../src/services/perf.execution.service');

  console.log(`\n  ${'Script'.padEnd(40)} ${'p95'.padEnd(8)} ${'p99'.padEnd(8)} ${'ErrRate'.padEnd(10)} Verdict`);
  console.log(`  ${'─'.repeat(80)}`);

  for (const r of allResults) {
    if (r.skipped || r.dryRun || r.verdict === 'data-invalid') continue;

    if (r.baselineDegraded && r.verdict === 'pass') r.verdict = 'warn';

    const m = r.metrics || {};
    const verdictLabel = r.verdict === 'pass'
      ? `${C.green}pass${C.reset}`
      : r.verdict === 'warn' ? `${C.yellow}warn${C.reset}` : `${C.red}fail${C.reset}`;

    console.log(
      `  ${r.basename.padEnd(40)} ${String(Math.round(m.p95 || 0)).padEnd(8)} ` +
      `${String(Math.round(m.p99 || 0)).padEnd(8)} ` +
      `${String((m.errorRate || 0).toFixed(4)).padEnd(10)} ` +
      verdictLabel
    );

    if (r.verdict === 'pass') {
      updateBaseline(`${r.storyKey}_${r.testType}`, m, r.verdict);
    }

    if (r.verdict === 'pass')      passCount++;
    else if (r.verdict === 'warn') warnCount++;
    else                           failCount++;
    totalRun++;
  }

  stageLog(3, 'Evaluate thresholds + baseline comparison', `DONE (${elapsed(s3)}s)`);

  // ──────────────────────────────────────────────────────────────────────────
  // Stage 4 — Sync to Zephyr + create Jira bugs
  // ──────────────────────────────────────────────────────────────────────────
  stageLog(4, 'Sync to Zephyr + create Jira bugs', flags.skipSync ? 'SKIPPED' : 'RUNNING');
  const s4 = Date.now();
  let zapSyncAllFailed = false;
  if (!flags.skipSync && !flags.dryRun) {
    try {
      const { retry } = require('../src/utils/retry');
      const zephyrRun = require('../src/tools/zephyrTestRun.client');
      const jiraBug = require('../src/tools/jiraBug.client');

      // Resolve a Zephyr Test Cycle ID. If ZEPHYR_CYCLE_ID is not set we skip live sync.
      let runId = (process.env.ZEPHYR_CYCLE_ID || '').trim();
      if (!runId) {
        try {
          const storyKey = (allResults.find(r => r.storyKey) || {}).storyKey
            || process.env.ISSUE_KEY || 'PERF';
          const ts = new Date().toISOString().slice(0, 19).replace('T', '_').replace(/:/g, '-');
          const runName = `PerfRun-${storyKey}-${ts}`;
          const run = await retry(() => zephyrRun.createTestRun(null, runName, {
            comment: `Auto-created performance test run for ${storyKey}. Triggered: ${new Date().toISOString()}`
          }), 3, 1500);
          runId = String(run.id);
          console.log(`  ${C.green}✓${C.reset} Created Zephyr perf test cycle: ${runId}`);
          logger.info(`[run-perf] auto-created perf run ${runId}`);
        } catch (e) {
          const detail = e.response?.data ? JSON.stringify(e.response.data) : e.message;
          console.warn(`  ${C.yellow}⚠ Could not auto-create perf test run — Zephyr sync will be skipped: ${detail}${C.reset}`);
          logger.warn(`[run-perf] run auto-create failed: ${detail}`);
        }
      }

      const tcMapPath = path.join(ROOT, 'tests', 'perf', 'perf-testcase-map.json');
      let tcMap = {};
      if (fs.existsSync(tcMapPath)) {
        try { tcMap = JSON.parse(fs.readFileSync(tcMapPath, 'utf8')); } catch { /* ignore */ }
      }

      const verdictToZephyr = { pass: 'Passed', warn: 'Blocked', fail: 'Failed', 'data-invalid': 'NotExecuted' };

      let syncPassCount = 0;
      let syncFailCount = 0;
      const syncable = allResults.filter(r => !r.skipped && !r.dryRun && tcMap[r.basename]);
      const totalSyncAttempts = syncable.length;

      for (const r of allResults) {
        if (r.skipped || r.dryRun) continue;
        const status = verdictToZephyr[r.verdict] || 'Blocked';
        const tcKey  = tcMap[r.basename] || tcMap[`${r.storyKey}_${r.testType}`] || tcMap[r.storyKey];
        const m      = r.metrics || {};

        const comment = [
          `Test type  : ${r.testType}`,
          `p95        : ${Math.round(m.p95 || 0)} ms`,
          `p99        : ${Math.round(m.p99 || 0)} ms`,
          `Error rate : ${((m.errorRate || 0) * 100).toFixed(2)}%`,
          `Max VUs    : ${m.vusMax || 0}`,
          (r.changePct !== null && r.changePct !== undefined) ? `Baseline Dp95 : ${r.changePct > 0 ? '+' : ''}${r.changePct}%`    : null,
          (r.changePct99 !== null && r.changePct99 !== undefined) ? `Baseline Dp99 : ${r.changePct99 > 0 ? '+' : ''}${r.changePct99}%` : null,
          (r.trend !== null && r.trend !== undefined) ? `Trend         : ${r.trend}`                                          : null,
        ].filter(Boolean).join('\n');

        if (tcKey) {
          if (!runId) {
            console.log(`  ${C.yellow}⚠ Skipping Zephyr sync (no run id): ${r.basename}${C.reset}`);
          } else {
          try {
            await retry(() => zephyrRun.createExecution(
              runId,
              tcKey,
              status,
              { comment }
            ), 3, 1500);
            console.log(`  ${C.green}✓ Zephyr synced: ${r.basename} → ${status}${C.reset}`);
            syncPassCount++;
          } catch (e) {
            const detail = e.response?.data ? JSON.stringify(e.response.data) : e.message;
            logger.warn(`[run-perf] Zephyr sync failed for ${r.basename}: ${detail}`);
            console.warn(`  ${C.yellow}⚠ Zephyr sync failed: ${r.basename} — ${detail}${C.reset}`);
            syncFailCount++;
          }
          }
        } else {
          console.log(`  ${C.dim}No Zephyr test case mapped for: ${r.basename}${C.reset}`);
        }

        if (r.verdict === 'fail' && !flags.skipBugs) {
          const breach = (r.breaches || [])[0] || {};
          const bugSummary = `Perf failure: ${r.basename} — p95 ${breach.actual}ms exceeded ${breach.limit}ms`;
          const breachDetails = (r.breaches || []).map(b => `  - ${b.metric}: actual=${b.actual}, limit=${b.limit}`).join('\n');
          try {
            await retry(() => jiraBug.createBug(
              { title: bugSummary, error: breachDetails, file: r.scriptPath },
              process.env.ISSUE_KEY
            ), 3, 1500);
            console.log(`  ${C.red}Bug created: ${r.basename}${C.reset}`);
          } catch (e) {
            logger.warn(`[run-perf] Jira bug creation failed for ${r.basename}: ${e.message}`);
          }
        }
      }

      console.log(`  [Stage 4] Zephyr sync — ${syncPassCount} passed, ${syncFailCount} failed`);
      if (syncFailCount > 0 && syncPassCount === 0 && syncFailCount === totalSyncAttempts && totalSyncAttempts > 0) {
        zapSyncAllFailed = true;
      }
    } catch (err) {
      logger.error(`[run-perf] Stage 4 error: ${err.message}`);
      console.error(`  ${C.yellow}Stage 4 non-fatal error: ${err.message}${C.reset}`);
    }
  }
  if (!flags.skipSync) stageLog(4, 'Sync to Zephyr + create Jira bugs', `DONE (${elapsed(s4)}s)`);

  // ──────────────────────────────────────────────────────────────────────────
  // Stage 5 — Generate performance report
  // ──────────────────────────────────────────────────────────────────────────
  stageLog(5, 'Generate performance HTML report', flags.skipReport ? 'SKIPPED' : 'RUNNING');
  const s5 = Date.now();
  if (!flags.skipReport) {
    try {
      const { generatePerfReport } = require('./generate-perf-report');
      const outputDir = path.join(ROOT, 'custom-report', 'perf');
      generatePerfReport(allResults, null, outputDir);
      console.log(`  ${C.green}✓ Report written to custom-report/perf/index.html${C.reset}`);
    } catch (err) {
      logger.error(`[run-perf] Stage 5 error: ${err.message}`);
      console.error(`  ${C.yellow}Stage 5 non-fatal error: ${err.message}${C.reset}`);
    }
  }
  if (!flags.skipReport) stageLog(5, 'Generate performance HTML report', `DONE (${elapsed(s5)}s)`);

  // ──────────────────────────────────────────────────────────────────────────
  // Stage 6 — Git agent
  // ──────────────────────────────────────────────────────────────────────────
  stageLog(6, 'Git Agent — auto-commit + push', flags.skipGit ? 'SKIPPED' : 'RUNNING');
  const s6 = Date.now();
  if (!flags.skipGit && !flags.dryRun) {
    try {
      const gitSync = require('./git-sync');
      if (typeof gitSync.run === 'function') {
        if (zapSyncAllFailed) {
          console.warn(`\n  ${C.yellow}⚠  ZEPHYR SYNC FAILED — all Zephyr execution syncs failed. Results were NOT recorded in Zephyr.${C.reset}\n`);
          logger.warn('[run-perf] zapSyncAllFailed=true — all Zephyr syncs failed this run');
        }
        await gitSync.run();
        console.log(`  ${C.green}✓ Git sync complete${C.reset}`);
      }
    } catch (err) {
      logger.error(`[run-perf] Stage 6 error: ${err.message}`);
      console.error(`  ${C.yellow}Stage 6 non-fatal error: ${err.message}${C.reset}`);
    }
  }
  if (!flags.skipGit) stageLog(6, 'Git Agent — auto-commit + push', `DONE (${elapsed(s6)}s)`);

  // ──────────────────────────────────────────────────────────────────────────
  // Final banner
  // ──────────────────────────────────────────────────────────────────────────
  const totalTime = elapsed(pipelineStart);
  console.log(`\n${C.bold}${C.white}╔══════════════════════════════════════════════════════╗`);
  console.log(`║  Performance Pipeline Complete                       ║`);
  console.log(`╠══════════════════════════════════════════════════════╣`);
  console.log(`║  Scripts run : ${String(totalRun).padEnd(37)}║`);
  console.log(`║  Pass        : ${C.green}${String(passCount).padEnd(37)}${C.reset}${C.bold}${C.white}║`);
  console.log(`║  Warn        : ${C.yellow}${String(warnCount).padEnd(37)}${C.reset}${C.bold}${C.white}║`);
  console.log(`║  Fail        : ${C.red}${String(failCount).padEnd(37)}${C.reset}${C.bold}${C.white}║`);
  console.log(`║  Total time  : ${String(totalTime + 's').padEnd(37)}║`);
  if (flags.dryRun) console.log(`║  ${C.yellow}DRY-RUN — no k6 scripts were executed${C.reset}${C.bold}${C.white}               ║`);
  console.log(`╚══════════════════════════════════════════════════════╝${C.reset}\n`);
}

main().catch(err => {
  logger.error(`[run-perf] Fatal: ${err.message}`);
  console.error(`\n${C.red}FATAL: ${err.message}${C.reset}\n`);
  process.exit(1);
});
